version: "2"
services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: lake-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/php-fpm/conf.d/99-overrides.ini
    ports:
      - ${PHP_PORT}:80

networks:
  default:
    external:
      name: ${NETWORK_DEFAULT}
